AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for a a serverless API

Parameters:
  ApplicationName:
    Type: String
    Default: 'serverless-api'

Resources:
  
  APIFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ApplicationName}-api-lambda'
      Handler: ./api/dist/index.handler
      Role: 
        Fn::ImportValue:
          !Sub '${ApplicationName}-lambda'
      Code:
        ZipFile: |            ## Placeholder code to create a resource.
          exports.handler = async (event) => {
            console.log("Hello, World!");
            return {
              statusCode: 200,
              body: JSON.stringify('Hello from Lambda!'),
            };
          };
      Runtime: nodejs20.x
      Timeout: 5

# Outputs:
#   ApiEndpoint:
#     Description: "API Gateway endpoint URL"
#     Value: !Sub "https://${HelloWorldApiGateway}.execute-api.${AWS::Region}://"