name: Tear Down a Project

on:
  workflow_dispatch:

jobs:
  initialize:
    name: cleanup-aws-resources
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials for deployment
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          output-credentials: true
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: cleanup aws resources
        id: cleanup
        run: |
          application_name=$(npm --loglevel silent run name)
          chmod +x ./aws-resources/scripts/cleanup.sh
          ./aws-resources/scripts/cleanup.sh $application_name