name: Deploy a Project

on:
  workflow_dispatch:
    inputs:
      target_job:
        description: 'Choose a job to run.'
        type: choice
        options:
        - deploy-aws-resources
        - deploy-api-lambda
        required: true
      release_type:
        description: 'Choose a type of release.'
        type: choice
        options:
        - patch
        - minor
        - major
        required: true
        default: patch

jobs:

  aws-resources:
    name: deploy-aws-resources
    if: ${{ github.event.inputs.target_job == 'deploy-aws-resources' }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Configure AWS Credentials for deployment
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          output-credentials: true
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: update-version
        id: update-version
        run: |
          npm version ${{ github.event.inputs.release_type }} --no-git-tag-version
          artifact_version=$(npm --loglevel silent run version)
          application_name=$(npm --loglevel silent run name)
          echo "application-name=$application_name" >> "$GITHUB_OUTPUT"
          echo "artifact-version=$artifact_version" >> "$GITHUB_OUTPUT"
      - name: Deploy AWS Resources
        id: deploy-aws-resources
        run: |
          chmod +x ./aws-resources/scripts/deploy.sh
          ./aws-resources/scripts/deploy.sh ${{ steps.update-version.outputs.application-name }}
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update project version
      - name: Upload Application Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.update-version.outputs.application-name }}-${{ steps.update-version.outputs.artifact-version }}
          path: ./
          overwrite: true
          if-no-files-found: warn
          retention-days: 1

  api-lambda:
    name: deploy-api-lambda
    if: ${{ github.event.inputs.target_job == 'deploy-api-lambda' }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Configure AWS Credentials for deployment
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          output-credentials: true
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: update-version
        id: update-version
        run: |
          npm version ${{ github.event.inputs.release_type }} --no-git-tag-version
          application_name=$(npm --loglevel silent run name)
          artifact_version=$(npm --loglevel silent run version)
          echo "application-name=$application_name" >> "$GITHUB_OUTPUT"
          echo "artifact-version=$artifact_version" >> "$GITHUB_OUTPUT"
      - name: deploy lambda function
        id: deploy-lambda-function
        run: |
          chmod +x ./api/scripts/build.sh
          chmod +x ./api/scripts/deploy.sh
          ./api/scripts/build.sh ${{ steps.update-version.outputs.artifact-version }}
          ./api/scripts/deploy.sh ${{ steps.update-version.outputs.application-name }} ${{ steps.update-version.outputs.artifact-version }}
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update project version
      - name: Upload Application Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.update-version.outputs.application-name }}-${{ steps.update-version.outputs.artifact-version }}
          path: ./
          overwrite: true
          if-no-files-found: warn
          retention-days: 1