name: Deploy a Project

on:
  workflow_dispatch:
    inputs:
      target_job:
        description: 'Choose a job to run.'
        type: choice
        options:
        - deploy-aws-resources
        - deploy-api-lambda
        - all
        required: true
      release_type:
        description: 'Choose a type of release.'
        type: choice
        options:
        - patch
        - minor
        - major
        required: true
        default: patch

jobs:

  update-artifact-version:
    name: update-artifact-version
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: update-version
        id: update-version
        run: |
          npm version ${{ github.event.inputs.release-type }}

  store-artifact:
    name: initialize-artifact_version
    needs: aws-resources || api-lambda
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: extract-version
        id: extract-version
        run: |
          artifact_version=$(npm --loglevel silent run version)
          echo "artifact-version=$artifact_version" >> "$GITHUB_OUTPUT"
      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.deploy-lambda-function.outputs.artifact-version }}
          path: ./
          overwrite: true
          if-no-files-found: warn
          retention-days: 1

  aws-resources:
    name: deploy-aws-resources
    needs: update-artifact-version 
    if: ${{ github.event.inputs.target_job == 'deploy-aws-resources' || github.event.inputs.target_job == 'all' }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials for deployment
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          output-credentials: true
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: deploy aws resources
        id: deploy-aws-resources
        run: |
          echo "The repositry name is: ${{ vars.APPLICATION_NAME }}"
          echo "Current Directory is: $PWD"
          chmod +x ./scripts/initialize.sh
          ./scripts/initialize.sh ${{ vars.APPLICATION_NAME }}

  api-lambda:
    name: deploy-api-lambda
    needs: update-artifact-version && aws-resources
    if: ${{ github.event.inputs.target_job == 'deploy-api-lambda' || github.event.inputs.target_job == 'all' }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials for deployment
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          output-credentials: true
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: deploy lambda function
        id: deploy-lambda-function
        run: |
          chmod +x ./api/scripts/build.sh
          chmod +x ./api/scripts/deploy.sh
          ./api/scripts/build.sh ${{ github.event.inputs.release-type }}
          ./api/scripts/deploy.sh ${{ vars.APPLICATION_NAME }}